id: PB4067832
initial_creation_type: input
source_metadata:
  title: 'Asaṅga: Triśatikāyāḥ Prajñāpāramitāyāḥ Kārikāsaptatiḥ'
  language: zh
  volumes:
    12ae138eb7ee4787bf1f3e7c67bb3a38:
      title: Colophon
      base_file: Colophon.txt
      work_id: W719420C3
    85a7a4ceffe94b6388d2304d4924751b:
      title: Preface
      base_file: Preface.txt
      work_id: W7D67756E
    d63d7e6ccd854163923f854a396e55e7:
      title: Title
      base_file: Title.txt
      work_id: W4D4C128D
    79cc52c62ff84b6ab984ba2730dd2eb2:
      title: Verses 1-20
      base_file: Verses 1-20.txt
      work_id: WA256A65F
    c9626b927bf24a88a55a61851faf545b:
      title: Verses 21-40
      base_file: Verses 21-40.txt
      work_id: W7DD10A7F
    99a0379a272a4481a20996074f03976a:
      title: Verses 41-60
      base_file: Verses 41-60.txt
      work_id: WDCDF8BBB
    c2e4895a301e49ca9015eb76e060994f:
      title: Verses 61-77
      base_file: Verses 61-77.txt
      work_id: W71414469
  chapter_to_tile: {}
created_at: '2022-03-01T23:04:08.714835'
last_modified_at: '2022-03-01T23:04:08.714841'
